//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_KEMR_Migration_Tool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PR_KEMR_Migration_Tool.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;encounters&quot;:[
        ///      &quot;ed40c9f1-e548-4e4c-823b-193f8d6ba73f&quot;
        ///   ]
        ///}.
        /// </summary>
        internal static string encounter_temp {
            get {
                return ResourceManager.GetString("encounter_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;encounterDatetime&quot;: &quot;2023-01-20T12:42:25.000Z&quot;,
        ///  &quot;patient&quot;: &quot;b5b7dbf8-88f8-427c-a2e5-55605e26dda7&quot;,
        ///  &quot;encounterType&quot;: &quot;ea68aad6-4655-4dc5-80f2-780e33055a9e&quot;,
        ///  &quot;location&quot;: &quot;e629d11c-cb0d-4f6d-a98c-99f8ca3e080a&quot;,
        ///  &quot;encounterProviders&quot;: [
        ///    {
        ///      &quot;provider&quot;: &quot;48b55692-e061-4ffa-b1f2-fd4aaf506224&quot;,
        ///      &quot;encounterRole&quot;: &quot;a0b03050-c99b-11e0-9572-0800200c9a66&quot;
        ///    }
        ///  ],
        ///  &quot;visit&quot;:&quot;2c5d6c83-1aef-4bd6-b128-368811dbceb3&quot;
        ///}.
        /// </summary>
        internal static string encounter_temp_2 {
            get {
                return ResourceManager.GetString("encounter_temp_2", resourceCulture);
            }
        }
    }
}
